async (page) => {
  const errors = [];
  const requests = [];
  page.on('pageerror', error => errors.push(error.message));
  const check = (ok, label) => { if (!ok) throw new Error(label); };
  const session = { access_token: 'test-token', refresh_token: 'test-refresh', expires_in: 3600, user: { id: 'test-user', email: 'test@example.com' } };
  await page.route('**/auth/v1/**', async route => {
    const url = route.request().url();
    const body = route.request().postDataJSON();
    requests.push({ url, body });
    if (url.includes('grant_type=password')) return route.fulfill({ status: 400, contentType: 'application/json', body: JSON.stringify({ msg: 'Invalid login credentials' }) });
    if (url.includes('/verify') && body.token === '000000') return route.fulfill({ status: 403, contentType: 'application/json', body: JSON.stringify({ msg: 'Token has expired or is invalid' }) });
    return route.fulfill({ contentType: 'application/json', body: JSON.stringify(url.includes('/verify') ? session : url.endsWith('/user') ? session.user : {}) });
  });
  await page.route('**/rest/v1/**', route => route.fulfill({ contentType: 'application/json', body: JSON.stringify([{ tasks: [], settings: {}, templates: [] }]) }));
  await page.goto('http://127.0.0.1:4194/index.html');
  await page.evaluate(() => localStorage.clear());
  await page.reload();
  await page.locator('#accountStatus').click();
  await page.locator('#authEmail').fill('test@example.com');
  await page.locator('#authPassword').fill('dummy-password');
  await page.locator('#authSubmitBtn').click();
  await page.waitForFunction(() => document.querySelector('#authStatusText').textContent.includes('邮箱或密码不正确'));
  await page.locator('#authForgotBtn').click();
  check(!await page.locator('#authPassword').isVisible(), 'recovery hides password');
  await page.locator('#authSubmitBtn').click();
  await page.waitForFunction(() => document.querySelector('#authStatusText').textContent.includes('你将收到重置邮件'));
  check(requests.some(r => r.url.includes('/recover?redirect_to=') && r.body.email === 'test@example.com'), 'recovery API');
  await page.locator('#authModeBtn').click();
  await page.locator('#authOtpModeBtn').click();
  await page.locator('#authSendCodeBtn').click();
  await page.waitForFunction(() => document.querySelector('#authStatusText').textContent.includes('验证码邮件已发送'));
  check(requests.some(r => r.url.includes('/otp?') && r.body.create_user === false), 'OTP does not create account');
  check(await page.locator('#authSendCodeBtn').isDisabled(), 'resend cooldown');
  await page.locator('#authOtp').fill('000000');
  await page.locator('#authSubmitBtn').click();
  await page.waitForFunction(() => document.querySelector('#authStatusText').textContent.includes('已过期'));
  await page.locator('#authOtp').fill('123456');
  await page.locator('#authSubmitBtn').click();
  await page.waitForFunction(() => document.querySelector('#accountStatus').textContent === '已同步');
  await page.locator('#authForm').waitFor({ state: 'hidden' });
  await page.evaluate(async () => { await handleAuthRedirect('http://127.0.0.1:4194/index.html#access_token=test-token&refresh_token=test-refresh&type=recovery'); });
  check(await page.locator('#authPasswordConfirm').isVisible(), 'recovery callback opens password form');
  await page.locator('#authPassword').fill('new-test-password');
  await page.locator('#authPasswordConfirm').fill('different-password');
  await page.locator('#authSubmitBtn').click();
  check(!requests.some(r => r.url.endsWith('/user') && r.body?.password), 'mismatch prevents reset');
  await page.locator('#authPasswordConfirm').fill('new-test-password');
  await page.locator('#authSubmitBtn').click();
  await page.locator('#authForm').waitFor({ state: 'hidden' });
  check(requests.some(r => r.url.endsWith('/user') && r.body?.password === 'new-test-password'), 'password update API');
  await page.locator('#accountStatus').click();
  await page.locator('#logoutBtn').click();
  await page.locator('#accountStatus').click();
  await page.locator('#authModeBtn').click();
  await page.locator('#authEmail').fill('test@example.com');
  await page.locator('#authPassword').fill('dummy-password');
  await page.locator('#authSubmitBtn').click();
  await page.waitForFunction(() => document.querySelector('#authStatusText').textContent.includes('确认邮件已发送'));
  await page.setViewportSize({ width: 390, height: 844 });
  await page.locator('#authModeBtn').click();
  await page.locator('#authOtpModeBtn').click();
  await page.screenshot({ path: 'auth-mobile.png' });
  const bounds = await page.locator('#authSubmitBtn').boundingBox();
  check(bounds && bounds.y >= 0 && bounds.y + bounds.height <= 844, 'mobile submit visible');
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.screenshot({ path: 'auth-desktop.png' });
  check(errors.length === 0, 'page errors: ' + errors.join(', '));
  console.log('PASS: wrong password, recovery email, OTP send/cooldown/invalid/success, reset callback/validation/save, signup, mobile bounds, no page errors. APIs mocked; no real email sent.');
}
